
# # # # # # # # # # # # # # # # # # # # # # # # # #
# Plotting routines for stats generated by PyMLMC
# TODO: add paper, description and link
#
# Jonas Sukys
# CSE Lab, ETH Zurich, Switzerland
# sukys.jonas@gmail.com
# All rights reserved.
# # # # # # # # # # # # # # # # # # # # # # # # # #

# === global imports

import pylab
import numpy

styles = {}
styles ['mean']             = 'b-'
styles ['std. deviation']   = 'r--'
styles ['percentile']       = 'g--'

# plot each stat
def plot_stats (qoi, stats):
  
  for name, stat in stats.iteritems():
    
    ts = numpy.array ( stat.meta ['t'] )
    vs = numpy.array ( stat.data [qoi] )
    
    style = styles [name] if name in styles else ''
    
    # stat-specific plotting
    if name == 'std. deviation' and 'mean' in stats:
      ms = numpy.array ( stats ['mean'] .data [qoi] )
      pylab.plot (ts, ms + vs, style, label='mean +/- std. dev.')
      pylab.plot (ts, ms - vs, style)
    
    # general plotting
    else:  
      pylab.plot (ts, vs, style, label=name)
  
  pylab.legend (loc='best')

def plot_mlmc_stats (qoi, stats, infolines, save):
  
  pylab.figure ( figsize = (8,6) )
  
  #TODO: infolines
  
  pylab.title ( 'estimated statistics for %s' % qoi )
  plot_stats (qoi, stats)
  
  if save: pylab.savefig (save)
  pylab.show ()

def plot_mc_stats (qoi, mcs, infolines, save):
  
  pylab.figure ( figsize = ( 2 * 8, 6 * len(mcs) ) )
  
  #TODO: infolines
  
  levels = len(mcs) / 2 + 1
  
  for mc in mcs:
    
    pylab.subplot ( levels, 2, mc.level + 1 + (mc.type == 1) * levels )
    pylab.title ( 'estimated statistics for %s (level %d)' % (qoi, mc.level) )
    plot_stats ( qoi, mc.stats )
  
  if save: pylab.savefig (save)
  pylab.show ()
